import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import LightRays from "@/components/LightRays";
// import { ThemeProvider } from "next-themes";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
    <html lang="en" className="dark" style={{ colorScheme: 'dark' }}>
      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div style={{ width: "100%", height: "100vh", position: "relative" }}>
      <LightRays
        raysOrigin="top-center"
        raysColor="#4191ff"
        raysSpeed={1.6}
        lightSpread={0.5}
        rayLength={5.9}
        followMouse={true}
        mouseInfluence={0.3}
        noiseAmount={0}
        distortion={0}
        className="custom-rays"
      />
      {/* <ThemeProvider attribute="class" defaultTheme="dark" enableSystem> */}
        {children}
        </div>
    {/* </ThemeProvider> */}
      </body>
    </html>
  );
}
